name: comscore
channels:
  - conda-forge
  - defaults
dependencies:
  - python[version='<3.11']
  - jupyterlab[version=3.5.2]
  - pytest[version=7.2.1]
  - typer[version=0.7.0]
  - rich[version=12.6.0]
  - shellingham[version=1.5.0.post1]
  - boto3[version=1.26.50]
  - jinja2[version=3.1.2]
  - pyyaml[version=6.0]
  - pandas[version=1.5.2]
  - pyarrow[version=10.0.1]
  - seaborn[version=0.12.2]

